services:
  asherah:
    build: ./asherah
    container_name: asherah_simulator
    hostname: asherah
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    environment:
      - MODBUS_PORT=502
      - PLC_IP=10.100.1.20
      - PLC_PORT=502
    volumes:
      - ./asherah/config.sh:/config.sh
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.all.arp_accept=0
      - net.ipv4.conf.default.arp_accept=0
      - net.ipv4.conf.all.arp_announce=2
      - net.ipv4.conf.all.arp_ignore=1

  scada_db:
    build: ./scada_db
    container_name: scada_mysql
    hostname: scada-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=scadalts
    volumes:
      - mysql_data:/var/lib/mysql
    command: --log_bin_trust_function_creators=1
    expose: 
      - "3306"
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.all.arp_accept=0
      - net.ipv4.conf.default.arp_accept=0
      - net.ipv4.conf.all.arp_announce=2
      - net.ipv4.conf.all.arp_ignore=1

  scadalts:
    build: ./scadalts
    container_name: scadalts
    hostname: scada
    cap_add:
      - NET_ADMIN  
    ports:
      - "8081:8080"
      - "8000:8000"
    environment:
      - CATALINA_OPTS=-Xmx2G -Xms2G
    volumes:
      - scadalts_logs:/usr/local/tomcat/logs
    depends_on:
      - scada_db
    expose: 
      - "8080"
      - "8000"
    links:
      - scada_db:database
    restart: unless-stopped
    

  attacker:
    build: ./attacker
    container_name: attacker_station
    hostname: attacker
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ./attacker/scripts:/root/scripts
      - ./attacker/logs:/root/logs
    stdin_open: true
    privileged: true
    tty: true
    restart: unless-stopped

volumes:
  mysql_data:
  scadalts_logs:
  elasticsearch_data:
  kibana_data:
  suricata_data:
