services:
  asherah:
    networks:
      ics_network:
        ipv4_address: 172.20.0.10
    ports:
      - "5020:502"

  scada_db:
    networks:
      ics_network:
        ipv4_address: 172.20.0.31

  scadalts:
    networks:
      ics_network:
        ipv4_address: 172.20.0.30

  attacker:
    networks:
      ics_network:
        ipv4_address: 172.20.0.100

networks:
  ics_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
    driver_opts:
      com.docker.network.bridge.name: br-ics
